---
  name:
  # Controls when the workflow will run
  on:
    release:
      types: [created]
    workflow_dispatch:
  defaults:
    run:
      working-directory: .

  # The sequence of runs in this workflow:
  jobs:
    quality:
      runs-on: ubuntu-latest
      steps:
        - name: Check OS Version
          run: lsb_release -a
        - name: Show Kernel Information
          run: uname -a
        - name: Check out Repository Code
          uses: actions/checkout@v4
          with:
            submodules: true # Fetch submodules
            fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
        - name: Set up the environment
          uses: ./.github/actions/setup-zig-env
        - name: Get Release Number
          id: get_release
          uses: bruceadams/get-release@v1.3.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Build binary
          run: just build
        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1.0.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.get_release.outputs.upload_url }}
            asset_path: ./zig-out/bin/kiwiRTOS.bin
            asset_name: kiwiRTOS.bin
            asset_content_type: application/octet-stream
        - name: Upload Release Asset
          uses: actions/upload-release-asset@v1.0.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.get_release.outputs.upload_url }}
            asset_path: ./zig-out/bin/kiwiRTOS.img
            asset_name: kiwiRTOS.img
            asset_content_type: application/octet-stream
